[package]
name = "viou"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = { version = "0.92", default-features = false, features = ["tracking"] }
thiserror = "1.0.49"
